### ISSUE TITLE
Crontab config issue on Debian 8.9 and MySQL 5.5.57

### ISSUE THREAD

**Issue by be-mohand** [Amaury/Arkiv#2]
Hi,

Thank you for this great tool!

I am using Debian 8.9 and MySQL 5.5.57. I had no problem when configuring Akriv, but the crontab was not correctly added.

Here the output I get: 
```
HERE IS THE CRONTAB THAT IS ABOUT TO BE ADDED
# ARKIV backup
0 4,11,19 arkiv COPYING README.md * * /root/Arkiv/arkiv exec --config=~/.arkiv --log=/var/log/arkiv/arkiv.log --no-stdout
```

I suppose the "arkiv COPYING README.md" does not belong to the crontab.

I tried after that to execute:
```
/root/Arkiv/arkiv exec --config=~/.arkiv --log=/var/log/arkiv/arkiv.log --no-stdout
````
but I also have a failure:
```
mysqldump: unknown option '-s'
```
In /var/log/arkiv/arkiv.log:
```
[2017-10-19 12:35:56+02:00] ⚠ Unable to dump database 'mydbname'
```

<img width="867" alt="capture d ecran 2017-10-19 a 12 39 36" src="https://user-images.githubusercontent.com/575444/31767272-b32bb774-b4ca-11e7-8337-eef3ce3aaec7.png">

Thank you for your support.

**Comment by Amaury** [comment]
Hi Mohand,

Thank you for your message.
I pushed a bugfix. You can try the version 0.9.1, it should correct these bugs.

Sorry for the inconvenience.

Best regards,

Amaury
